apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: wrong-pod
  name: wrong-pod
  namespace: quota
spec:
  containers:
  - image: flask-app:v1
    name: wrong-pod
    resources:
      limits:
        memory: "250Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
